name: love_letters
description: Skeleton app for April challenge of flutterchallenge.dev

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  get_it: ^7.1.4
  shared_preferences: ^2.0.13
  animated_text_kit: ^4.2.1
  url_launcher: ^6.0.20
  confetti: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cup.png
